baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Vikas Rajpoot'

theme="hugo-PaperMod"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "work"
    name = "Work"
    title = "Work"
    url = "/work/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    title = "Contact"
    url = "/contact/"